#!/bin/bash
	printf "\n"
	printf "\n"
	printf "\n"
	printf "\n"
printf " \033[1;31m    ⣒⡺⢿⣿⣿⠶⠙⣛⣙⣛⠶       \n"
printf "     ⣿⡟⠺⣍⢶⣾⣿⣿⣿⣿⣿⠏⠁     \n"
printf "     ⣿⣿⣴⡜⠜⣿⣿⣿⣿⣿⣿⢀      \n"
printf "  ⠈⠐⠠⡻⣿⢸⣿⣶⣝⣿⣿⣿⡿⡣⠃      \n"
printf "      ⠉⠺⠌⠛⢿⣟⣌⠩⠟⠒⠁       \n"
printf "           ⠛⠛           \n"
printf " \e[38;5;82m          ⡇⣾             \n"
printf "   ⢀⣀⣀⣀⠄⠄⢀⣄⠄⡇             \n"
printf "   ⢶⣾⣿⣿⣿⣶⡄⢸⣿⡆⡇            \n"
printf "    ⠙⠻⠿⠛⠛⠋⠊⢟⠄⣾            \n"
printf "        ⣶⣿⡿⠃⠢⢰⠄           \n"
printf "        ⠉⠉⠁⠄⠄⣾⠄           \n"
printf "             ⡇            \n"
printf "             ⡇            \n"
printf "             ⢸⣴⣦⠄⢀⣤⣶⣶⣦⣄   \n"
printf "             ⢸⢿⡿⢡⣿⣿⣿⣿⡿⠛   \n"
printf "             ⡸⡀⢌⣤⣀⠄⠉⠁     \n"
printf "             ⣆⠁⠘⠿⠿⠷       \n"
printf "             ⡏            \n"
printf "             ⣧            \n"
printf "             ⢸            \n"
printf "             ⢸            \n"
printf "             ⢸            \n"
printf "             ⡇            \n"
printf "             ⡇            \n"
                          
                          

